import clsx from "clsx";
import { Suspense } from "react";
import { Provider } from "jotai";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/header/header";
import type { Metadata } from "next";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={clsx(geistSans.variable, geistMono.variable, "relative antialiased bg-black min-h-screen overflow-x-hidden bg-no-repeat has-[[data-home]]:bg-(image:--bg-home)", "has-[[data-theme]]:bg-(image:--bg-profile)")}>
        <Provider>
          <Suspense>
            <Header />
          </Suspense>
          <div className="sm:pt-32 pt-[4.375rem]">{children}</div>
          {modal}
        </Provider>
      </body>
    </html>
  );
}
