import clsx from "clsx";
import { Provider } from "jotai";
import { ModalContainer } from "@/components/modals/view";
import { geistSans, geistMono } from "@/styles/font";
import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={clsx(geistSans.variable, geistMono.variable, "antialiased bg-black overflow-x-hidden")}>
        <Provider>{children}</Provider>
        <ModalContainer />
      </body>
    </html>
  );
}
