import clsx from "clsx";
import { Provider } from "jotai";
import { ModalContainer } from "@/components/modals/view";
import { Header } from "@/components/header/header";
import { geistSans, geistMono } from "@/styles/font";
import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={clsx(geistSans.variable, geistMono.variable, "relative antialiased bg-black min-h-screen overflow-x-hidden", "has-[[data-theme]]:bg-no-repeat has-[[data-theme]]:bg-(image:--bg-profile)")}>
        <Provider>
          <Header />
          <div className="pt-32">{children}</div>
        </Provider>
        <ModalContainer />
      </body>
    </html>
  );
}
